# Generated by Django 4.0.3 on 2022-03-21 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField()),
                ('province', models.TextField()),
                ('code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StreetAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tblCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_desc', models.CharField(max_length=255)),
                ('units', models.IntegerField()),
                ('course_comments', models.TextField(max_length=255)),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='tblProject_Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_name', models.CharField(max_length=30)),
                ('transaction_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblStaff_Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_line', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tblStudent_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=255)),
                ('registration_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblStudent_Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reports_name', models.CharField(max_length=30)),
                ('student_records', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_system_records.tblstudent_registration')),
                ('transaction_reports', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_system_records.tblproject_transaction')),
            ],
        ),
        migrations.CreateModel(
            name='tblStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stfname', models.CharField(max_length=30)),
                ('stlname', models.CharField(max_length=30)),
                ('stcourse', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=12)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('adress', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_system_records.address')),
            ],
        ),
        migrations.CreateModel(
            name='tblStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('Iname', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=12)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('adress', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_system_records.address')),
            ],
        ),
        migrations.AddField(
            model_name='tblproject_transaction',
            name='staff_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_system_records.tblstaff'),
        ),
        migrations.AddField(
            model_name='tblproject_transaction',
            name='stundent_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_system_records.tblstudent'),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_system_records.streetaddress'),
        ),
    ]
